# Generated by Django 5.0.6 on 2025-08-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('tipo_contacto', models.CharField(choices=[('telefono', 'Teléfono'), ('email', 'Email'), ('presencial', 'Presencial'), ('chat', 'Chat'), ('otro', 'Otro')], default='telefono', max_length=50)),
                ('resultado', models.CharField(choices=[('contactado', 'Contactado exitosamente'), ('no_contactado', 'No se pudo contactar'), ('informacion_adicional', 'Se obtuvo información adicional'), ('seguimiento_requerido', 'Requiere seguimiento'), ('resuelto', 'Resuelto en esta atención')], default='contactado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
